### PR TITLE
Cache identifier client

### PR DESCRIPTION
**Pull request by mikedarcy**
I added code to cache the identifiers client which really helps when making multiple calls to the service, especially in batch mode. Yielded about a 3x performance improvement on my test system. Coupled with a similar bottleneck removal on the server side when making handle system requests, the result is an overall speedup of about 5-6x current perf! Also added a bit more info logging when batching.

### CODE REVIEW

**Comment by NickolausDS** [comment]
I switched the branch and am re-running tests. Tests may fail if the Mock now misses the changed property, but we can merge now and fix later.

**Comment by NickolausDS** [comment]
I'm a little curious why this resulted in such a perf boost. Does creating a client make a call out each time?

**Review by NickolausDS — APPROVED** [review]

**Comment by NickolausDS** [comment]
Tests passed, flake8 failed. Should be fine

**Comment by mikedarcy** [comment]
> I'm a little curious why this resulted in such a perf boost. Does creating a client make a call out each time?

The identifier client, which uses the globus sdk, which in turn uses requests to handle the HTTPS requests uses a requests.session object under the hood to cache the connection. By creating a new client for essentially every request, you are bypassing all of that optimization and doing a cold connection every request to the server, which includes all ssl connection establishment overhead and authorization overhead.

**Comment by NickolausDS** [comment]
Good writeup, thanks.

**Pull request merged**
