### PR TITLE
Switched CLI implementation from custom ArgumentParser to Click

### PR DESCRIPTION
**Pull request by NickolausDS**
These changes fully re-implement the Minid CLI from the custom Argument Parser to use click instead. All commands _should_ be unchanged. One exception is the `--locations` flag, which now must be specified as a comma-delimited list. (ex: `minid register foo.txt example.com/foo.txt,foo.example.com`)

@mikedarcy Please review, and let me know what you think. I haven't touched any of the tests yet. I'll rewrite those after we've finished making major decisions on the CLI.

### CODE REVIEW

**Review by mikedarcy — APPROVED** [review]
Looks good to me. Are we going to have another beta release with these updates?

**Comment by NickolausDS** [comment]
Great, I'll merge after adding tests. 

> Are we going to have another beta release with these updates?

That was my plan, yes. I had one other planned feature to add a config command, which would allow specifying alternatives for some fields. It would look like:
* `minid config --service identifires.fair-research.org`
* `minid config --name "Nickolaus Saint"`

After that, I was planning on cutting the Beta 5 release. Unless you can think of any other features to add, we should be ready for a stable release when we're comfortable.

**Comment by mikedarcy** [comment]
Sounds good to me. I like the idea of the `config` command. 👍

**Comment by NickolausDS** [comment]
Ported old tests to new click ones (Most did actually port well), removed unnecessary tests, and added a few new tests. Test coverage is near 98%, with unit tests only missing direct calls into the CLI module (as in `python minid/commands/main.py`). The new tests aren't perfect and there may still be bugs, but they should give us a pretty good baseline if a change breaks anything. 

CLI testing did reveal a bug in the Identifiers Service -- replacing a minid with itself causes a 500: 

    minid update minid.test:13vUxANTiDMko --replaced-by minid.test:13vUxANTiDMko

The new bugfixes don't change things around too much, so I'll go ahead and merge now. Happy to add/remove fixes if you catch anything afterwards.

**Pull request merged**
